BEGIN;
DROP TABLE IF EXISTS backups;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS deletion_requests;
DROP TABLE IF EXISTS consent_records;
DROP TABLE IF EXISTS taggings;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS data_dictionary;
DROP TABLE IF EXISTS anomaly_alerts;
DROP TABLE IF EXISTS analytics_hourly;
DROP TABLE IF EXISTS analytics_events;
DROP TABLE IF EXISTS notification_deliveries;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS document_revisions;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS group_buy_participants;
DROP TABLE IF EXISTS group_buys;
ALTER TABLE bookings DROP COLUMN IF EXISTS user_anonymized;
ALTER TABLE bookings DROP COLUMN IF EXISTS secure_notes;
ALTER TABLE users DROP COLUMN IF EXISTS anonymized_at;
ALTER TABLE users DROP COLUMN IF EXISTS is_admin;
COMMIT;
